Repository COSC481W-2022Winter/capstone-hackmcx, pull requests merged in 2022-04, with the labels that each got.

#96 enhancement: Implemented The User Login and Update User Information Page
  packages/hackmcx-api/src/controllers/users.controller.js
  packages/hackmcx-api/src/routers/v1/users.router.js
  packages/hackmcx-client/package-lock.json
  packages/hackmcx-client/package.json
  packages/hackmcx-client/src/App.js
  packages/hackmcx-client/src/AppNav.js
  packages/hackmcx-client/src/components/Login.js
  packages/hackmcx-client/src/components/Logout.js
  packages/hackmcx-client/src/components/UserProfile.js
  packages/hackmcx-client/src/components/authToken.js
  packages/hackmcx-client/src/components/updateAccountModal.js
Labels: enhancement, front end, sprint-3

#98 Enhancement ari cyrus loginfeatures
  packages/hackmcx-client/src/AppNav.js
  packages/hackmcx-client/src/components/Login.js
  packages/hackmcx-client/src/components/posts/CreatePost.js
  packages/hackmcx-client/src/components/posts/Post.js
  packages/hackmcx-client/src/components/posts/captions/CaptionCreation.js
  packages/hackmcx-client/src/components/posts/captions/Ratings.js
Labels: enhancement, front end, sprint-3

#102 fix: add checks for string length for input data
  packages/hackmcx-api/src/controllers/captions.controller.js
  packages/hackmcx-api/src/controllers/posts.controller.js
  packages/hackmcx-api/src/utils/validation.js
Labels: bug, backend, sprint-3

#103 Enhancement: Meaningful Seed Data
  packages/hackmcx-api/src/db/seeds/2022-02-15_1902_demo_posts.cjs
  packages/hackmcx-api/src/db/seeds/2022-03-09_1502_demo_captions.cjs
  packages/hackmcx-api/src/db/seeds/2022-03-09_1815_demo_users.cjs
Labels: backend, sprint-3

#110 feat: Add Password Update Endpoint and Increase JSON Size Limit
  packages/hackmcx-api/src/app.js
  packages/hackmcx-api/src/controllers/users.controller.js
  packages/hackmcx-api/src/routers/v1/users.router.js
  packages/hackmcx-api/src/utils/validation.js
Labels: enhancement, backend, sprint-4

#111 feat: Implemented the Account Creation Page
  packages/hackmcx-client/src/App.js
  packages/hackmcx-client/src/components/CreateAccount.js
  packages/hackmcx-client/src/components/Login.js
Labels: front end, sprint-4

#112 Enhancements ari cyrus uploadimages
  packages/hackmcx-client/src/components/UserProfile.js
  packages/hackmcx-client/src/components/posts/CreatePost.js
  packages/hackmcx-client/src/components/posts/Post.js
  packages/hackmcx-client/src/components/posts/PostList.js
  packages/hackmcx-client/src/components/updateAccountModal.js
Labels: enhancement, front end, sprint-4

#120 Fix Issues #119, #115, #118, #114
  packages/hackmcx-api/src/app.js
  packages/hackmcx-client/src/components/posts/CreatePost.js
  packages/hackmcx-client/src/components/posts/PostList.js
  packages/hackmcx-client/src/components/posts/captions/CaptionCreation.js
  packages/hackmcx-client/src/components/updateAccountModal.js
Labels: bug, demo-required
