Repository COSC481W-2022Winter/capstone-hackmcx, pull requests merged in 2022-02, with the labels that each got.

#24 feat: Add Post Endpoints and Migrations
  packages/hackmcx-api/dev.env
  packages/hackmcx-api/package-lock.json
  packages/hackmcx-api/package.json
  packages/hackmcx-api/src/app.js
  packages/hackmcx-api/src/clients/mariadb.js
  packages/hackmcx-api/src/controllers/example.controller.js
  packages/hackmcx-api/src/controllers/posts.controller.js
  packages/hackmcx-api/src/db/db.js
  packages/hackmcx-api/src/db/migrations/2022-02-15_2153_create_table_posts.cjs
  packages/hackmcx-api/src/db/seeds/2022-02-15_1902_demo_posts.cjs
  packages/hackmcx-api/src/index.js
  packages/hackmcx-api/src/models/posts.js
  packages/hackmcx-api/src/router.js
  packages/hackmcx-api/src/routers/example.router.js
  packages/hackmcx-api/src/routers/v1.router.js
  packages/hackmcx-api/src/routers/v1/posts.router.js
Labels: enhancement, sprint-1

#30 fix: Fix Error Handling for the POST posts Endpoint
  packages/hackmcx-api/src/controllers/posts.controller.js
Labels: bug, backend, sprint-1

#35 enhancement: Logo on Navbar implemented
  packages/hackmcx-client/package-lock.json
  packages/hackmcx-client/package.json
  packages/hackmcx-client/public/index.html
  packages/hackmcx-client/src/App.js
  packages/hackmcx-client/src/LandingPage.js
  packages/hackmcx-client/src/faviconButton.ico
Labels: enhancement, small, front end, sprint-1

#33 enhancement: Created Create Post Page
  packages/hackmcx-client/package-lock.json
  packages/hackmcx-client/src/App.js
  packages/hackmcx-client/src/CreatePost.js
Labels: enhancement, small, front end, sprint-1

#34 enhancement: Favicon replaced with logo
  packages/hackmcx-client/public/favicon.ico
Labels: enhancement, small, front end, sprint-1

#43 fix: Address Pre-Deployment Issues
  packages/hackmcx-client/.env.local
  packages/hackmcx-client/package-lock.json
  packages/hackmcx-client/public/imgs/logo.png
  packages/hackmcx-client/public/logo192.png
  packages/hackmcx-client/public/logo512.png
  packages/hackmcx-client/src/App.js
  packages/hackmcx-client/src/App.test.js
  packages/hackmcx-client/src/AppNav.js
  packages/hackmcx-client/src/CreatePost.js
  packages/hackmcx-client/src/LandingPage.js
  packages/hackmcx-client/src/PostPage.js
  packages/hackmcx-client/src/components/posts/CreatePost.js
  packages/hackmcx-client/src/components/posts/PostList.js
  packages/hackmcx-client/src/logo.svg
Labels: bug, front end, sprint-1
