Repository COSC481W-2022Winter/capstone-hackmcx, pull requests merged in 2022-03, with the labels that each got.

#64 feat: Add Migrations and Seed for Captions
  packages/hackmcx-api/src/db/migrations/2022-03-08_1129_create_table_captions.cjs
  packages/hackmcx-api/src/db/migrations/2022-03-09_1604_create_table_users.cjs
  packages/hackmcx-api/src/db/seeds/2022-03-09_1502_demo_captions.cjs
  packages/hackmcx-api/src/db/seeds/2022-03-09_1815_demo_users.cjs
Labels: backend, sprint-2

#66 feat: Implement GET /v1/users Endpoint
  packages/hackmcx-api/src/controllers/users.controller.js
  packages/hackmcx-api/src/routers/v1.router.js
  packages/hackmcx-api/src/routers/v1/users.router.js
Labels: backend, sprint-2

#65 feat: Added router & controller for Caption
  packages/hackmcx-api/src/controllers/captions.controller.js
  packages/hackmcx-api/src/controllers/posts.controller.js
  packages/hackmcx-api/src/routers/v1/posts.router.js
  packages/hackmcx-api/src/routers/v1/posts/captions.router.js
Labels: backend, sprint-2

#67 feat: Added POST endpoint for Users
  packages/hackmcx-api/src/controllers/users.controller.js
  packages/hackmcx-api/src/routers/v1/users.router.js
Labels: backend, sprint-2

#68 feat: Add Caption Rating Endpoint
  packages/hackmcx-api/src/controllers/captions.controller.js
  packages/hackmcx-api/src/db/seeds/2022-03-09_1502_demo_captions.cjs
  packages/hackmcx-api/src/routers/v1/posts/captions.router.js
Labels: backend, sprint-2

#74 enhancement: Create Creation component created
  packages/hackmcx-client/src/components/posts/IndividualPost.js
  packages/hackmcx-client/src/components/posts/captions/CaptionCreation.js
Labels: enhancement, front end, sprint-2

#77 enhancement: Updated Post Component
  packages/hackmcx-api/dev.env
  packages/hackmcx-client/build/asset-manifest.json
  packages/hackmcx-client/build/favicon.ico
  packages/hackmcx-client/build/imgs/logo.png
  packages/hackmcx-client/build/index.html
  packages/hackmcx-client/build/manifest.json
  packages/hackmcx-client/build/robots.txt
  packages/hackmcx-client/build/static/css/main.073c9b0a.css
  packages/hackmcx-client/build/static/css/main.073c9b0a.css.map
  packages/hackmcx-client/build/static/js/787.c313d2cc.chunk.js
  packages/hackmcx-client/build/static/js/787.c313d2cc.chunk.js.map
  packages/hackmcx-client/build/static/js/main.1ba0869a.js
  packages/hackmcx-client/build/static/js/main.1ba0869a.js.LICENSE.txt
  packages/hackmcx-client/build/static/js/main.1ba0869a.js.map
  packages/hackmcx-client/build/static/js/main.5f957568.js
  packages/hackmcx-client/build/static/js/main.5f957568.js.LICENSE.txt
  packages/hackmcx-client/build/static/js/main.5f957568.js.map
  packages/hackmcx-client/src/App.js
  packages/hackmcx-client/src/AppNav.js
  packages/hackmcx-client/src/components/UserProfile.js
  packages/hackmcx-client/src/components/posts/Post.js
  packages/hackmcx-client/src/components/posts/PostList.js
  packages/hackmcx-client/src/components/updateAccountModal.js
Labels: enhancement, front end, sprint-2

#76 enhancement: Implemented Rating Component
  packages/hackmcx-client/src/components/posts/IndividualPost.js
Labels: enhancement, front end, sprint-2

#78 enhancement: Multiple page layouts adjusted
  packages/hackmcx-client/src/components/posts/CreatePost.js
  packages/hackmcx-client/src/components/posts/IndividualPost.js
  packages/hackmcx-client/src/components/posts/Post.js
  packages/hackmcx-client/src/components/posts/PostList.js
  packages/hackmcx-client/src/components/posts/captions/CaptionCreation.js
Labels: enhancement, front end, sprint-2

#81 fix: remove duplicate posts with matching average
  packages/hackmcx-api/src/controllers/posts.controller.js
Labels: bug, backend

#90 feat: Add password & PUT endpoint to Users
  packages/hackmcx-api/package-lock.json
  packages/hackmcx-api/package.json
  packages/hackmcx-api/src/controllers/users.controller.js
  packages/hackmcx-api/src/db/migrations/2022-03-29_1746_alter_table_users.cjs
  packages/hackmcx-api/src/db/seeds/2022-03-09_1815_demo_users.cjs
  packages/hackmcx-api/src/db/seeds/2022-03-29_1757_update_demo_users.cjs
  packages/hackmcx-api/src/routers/v1/users.router.js
Labels: backend, sprint-3

#91 feature: Add /api/v1/users/_login endpoint
  packages/hackmcx-api/dev.env
  packages/hackmcx-api/package-lock.json
  packages/hackmcx-api/package.json
  packages/hackmcx-api/src/controllers/users.controller.js
  packages/hackmcx-api/src/routers/v1/users.router.js
  packages/hackmcx-api/src/utils/validation.js
Labels: backend, sprint-3

#92 feat: Add Token Authentication
  packages/hackmcx-api/src/middleware/auth.middleware.js
  packages/hackmcx-api/src/routers/v1/posts.router.js
Labels: backend, sprint-3

#93 feat: Add Authentication to POST/PUT endpoints
  packages/hackmcx-api/src/controllers/users.controller.js
  packages/hackmcx-api/src/routers/v1/posts/captions.router.js
  packages/hackmcx-api/src/routers/v1/users.router.js
Labels: backend, sprint-3
